shopwareBoostDay/platform

- changelog/_unreleased/2020-09-17-pass-all-non-defined-attributes-as-props-in-sw-button.md
- src/Administration/Resources/app/administration/src/app/component/base/sw-button/sw-button.html.twig
- src/Administration/Resources/app/administration/test/app/component/base/sw-button.spec.js
This change will pass all non-defined attributes of the `sw-button` to its children (`router-link`, `a` and `button`) as props through the use of `v-bind="$attrs"`.
- Create eg. a link type button and add the `download` attribute, like so:
```html
<sw-button
variant="primary"
:link="downloadLink"
:download="downloadFileName"
>
my download button
</sw-button>
```
- Observe the download file name is not used, while with this change it is.
> NEXT-10848 - Pass all non-defined attributes as props in sw-button

- changelog/_unreleased/2020-09-17-fix-category-name-overflow.md
- src/Administration/Resources/app/administration/src/app/component/tree/sw-tree-item/sw-tree-item.scss
- src/Administration/Resources/app/administration/src/app/component/tree/sw-tree/sw-tree.scss
This PR fixes the category names to overflow if they are too long. 
View without the change:
View with the change:
The cause for the behaviour was the use of the [experimental](https://developer.mozilla.org/de/docs/Web/CSS/width) value `max-content` for the width of tree-items. 
Give a category a too long name and the context menu trigger will disappear.
> NEXT-9166 - Fix long category names overflowing their boundaries

- changelog/_unreleased/2020-09-17-add-support-for-repository-autowiring.md
- src/Core/Framework/DependencyInjection/CompilerPass/EntityCompilerPass.php
- src/Core/Framework/Test/DependencyInjection/CompilerPass/EntityCompilerPassTest.php
- src/Docs/Resources/current/20-developer-guide/50-database.md
This change adds support for the Symfony DIC autowiring feature in combination with Shopware entity repositories.
Create a new service, configure it for being autowired and having the constructor signature `public function __construct(EntityRepositoryInterface $productRepository)`. Using this change, the new service will have the correct repository injected automatically.
> NEXT-10918 - Add entity repository autowiring

- changelog/_unreleased/2020-09-17-add-label-to-availabitlity-rule-in-shipping-method-detail.md
- src/Administration/Resources/app/administration/src/module/sw-settings-shipping/page/sw-settings-shipping-detail/sw-settings-shipping-detail.html.twig
this time with changelog
Adds a label to shipping method detail/create page, to show user that the availabitlity rule input field is required.
it uses a already existing translation.
create shipping method without setting a availability rule or try to update a existing shipment without setting the availability rule
- [X ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
> NEXT-7962 - Add label to shipping method detail fixes #73

- changelog/_unreleased/2020-09-17-fix-order-listing-sort-by-customer-name.md
- src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-list/index.js
Fixes error 400 when sorting on customer name in order list. 
Go to order list on default installation. Try to sort on customer name.
I choose to split sortBy by comma because refactoring listing sortBy to an array is out of scope for this issue.
> [NEXT-9716] Split sortBy to support multiple properties

- changelog/_unreleased/2020-09-17-fix-listingpage-pagination-arrows-always-visible.md
- changelog/readme.md
- src/Storefront/Resources/views/storefront/component/pagination.html.twig
1. What does this change do, exactly?
Hide prev arrows on first page and next arrows on last page in `pagination.html.twig`
2. Describe each step to reproduce the issue or behaviour.
Go to first page on homepage list
Got to last page on homepage list
> NEXT-9023 - Fix ListingPage pagination arrows always visible #44

- changelog/_unreleased/2020-09-17-minify-css.md
- src/Storefront/Theme/Autoprefixer.php
- src/Storefront/Theme/ThemeCompiler.php
Currently the CSS gets "deminified" by the autoprefixer, but there is currently no way to circumvent this, see:
https://github.com/padaliyajay/php-autoprefixer/pull/8
https://github.com/padaliyajay/php-autoprefixer/issues/10
"Manually" minify the CSS in the CSS compiler.
Look at the compiled CSS with and without this PR.
Fixes #65
> NEXT-8145 - minify compiled CSS fixes #65

- changelog/_unreleased/2020-09-17-directly-open-product-on-search-by-product-number.md
- src/Storefront/Controller/SearchController.php
Like in SW5, there should be an option to be redirected directly from search to product details when search gives only one result and/or search query is exact match fro the product number (and/or possibly some other fields like ean or manufacturer number).
It redirects from the listing page to the detail page when the searchPageLoader page only has got one result.
- Go to storefront
- Type an exactly article number to the search field and press enter
https://github.com/shopwareBoostDay/platform/issues/116
> NEXT-10857 - Directly open product on search by product number

- changelog/_unreleased/2020-09-17-add-empty-state-to-sw-property-search-result-list.md
- src/Administration/Resources/app/administration/src/app/component/base/sw-property-search/sw-property-search.html.twig
- src/Administration/Resources/app/administration/src/app/snippet/de-DE.json
- src/Administration/Resources/app/administration/src/app/snippet/en-GB.json
Shows an empty state in the sw-property-search when no results are found.
- Visit the product edit page in the Administration.
- Click on tab 'property assignment' 
- Search for the 'Available properties' 
- Type a non-existing searchphrase.
This is how it looked:
This is how it looks now:
> NEXT-9188 - Add empty state to sw-property-search result list

- changelog/_unreleased/2020-09-17-add-ability-to-search-by-custom-field-in-administration-backend.md
- src/Core/Checkout/Customer/CustomerDefinition.php
- src/Core/Content/Product/Aggregate/ProductManufacturer/ProductManufacturerDefinition.php
- src/Core/Content/Product/ProductDefinition.php
It gives possibility to search by Custom Fields in Administration.
It adds `SearchRanking` flag which is used by `EntityScoreQueryBuilder` to build queries based on the Term provided.
Example: Please create i.e. a product with Custom Field. Go to search field in Administration, fill in the Custom Field value (or part) and hit ENTER. The product should be returned in search results. It works for Products, Manufacturers and Customers in Administration only.
> NEXT-10855 - Add ability to search by Custom Fields in Admin Backend

- changelog/_unreleased/2020-09-17-improve-line-item-custom-field-rule-execution.md
- src/Core/Checkout/Cart/Rule/LineItemCustomFieldRule.php
- src/Core/Checkout/Test/Cart/Rule/LineItemCustomFieldRuleTest.php
- src/Core/Content/Rule/RuleValidator.php
- src/Core/System/CustomField/CustomFieldTypes.php
Fix handling of boolean custom fields in the `LineItemCustomFieldRule` by adding fallback values for the null-initialization in the rule builder and removing `NotEmpty` constraints for boolean fields in the rule condition.
See [this short video](https://vimeo.com/458984611/87e9e29df8) detailing the solution.
Fixes #115.
* Have custom field of boolean type (checkbox or switch)
* Add a line item custom field rule condition for this field and leave the checkbox unchecked
* Try to save the rule and be sad about the error message stating that a value is required
If you somehow manage to circumvent that (e.g. add the rule via the database directly), but are using the default null value from the administration (yes, a bit contrived):
* Use the rule for a promotion
* Try to add the promotion in …
> NEXT-10858 - Extract value constraints for line item custom field rule, allow empty bool value.

- changelog/_unreleased/2020-09-17-add-address-to-customer-selection-in-add-order.md
- src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-create-details-header/index.js
- src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-create-details-header/sw-order-create-details-header.html.twig
- src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-create/sw-order-create.scss
When you search for a customer it can happen that a customer has multiple accounts but with different addresses. By adding the address below the customer name it makes it more clear.
It displays the customer defaultBillingAddress below the customer and company name.
Go to Orders - Overview  and click 'Add order'. In the new page you can search for a customer. In the result list the customer info is displayed with the billingAddress info.
https://issues.shopware.com/issues/NEXT-8309
> NEXT-8309 - Add address to customer selection

- changelog/_unreleased/2020-09-17-add-autoscroll-to-listing.md
- src/Storefront/Resources/app/storefront/src/plugin/listing/listing.plugin.js
- src/Storefront/Resources/app/storefront/test/plugin/listing/listing.plugin.test.js
Add scroll-up in listing to get the user moved to the top of the loaded listing while they are switching pages on bottom navigation.
- change page of listing on the bottom navigation
- see user stucks on this position
> NEXT-9021 - Add autoscroll to listing

- changelog/_unreleased/2020-09-17-maintenance-forward.md
- src/Storefront/Controller/MaintenanceController.php
- src/Storefront/DependencyInjection/controller.xml
- src/Storefront/Framework/Routing/MaintenanceModeResolver.php
- src/Storefront/Framework/Routing/StorefrontSubscriber.php
- src/Storefront/Resources/views/storefront/page/error/error-maintenance.html.twig
- Added auto reload to `error-maintenance.html.twig` with new block `error_maintenance_script_reload`
-  Added new function `shouldRedirectToShop` to `MaintenanceModeResolver`
- Detail: this is necessary, cause the current implementation doesn't respect whitelistUrl
-  Added service `MaintenanceModeResolver` to `MaintenanceController`
- Detail: we need the new function of `MaintenanceModeResolver`
-  Added status code with `HTTP_SERVICE_UNAVAILABLE` to `MaintenanceController`
- Detail: This is the correct code for maintenance
-  Added header for `Retry-After` to `MaintenanceController`
- Detail: This is the needed for search engines
-  Added status code with `HTTP_TEMPORARY_REDIRECT` to the RedirectResponse to `maintenance.page`
- Detail: This is the needed for search engines
> NEXT-9121 - Redirect Maintenance

- changelog/_unreleased/2020-09-17-optimise-requests-in-localetolanguageservice.md
- src/Administration/Resources/app/administration/src/app/service/locale-to-language.service.js
The `LocaleToLanguageService` uses two separate requests in its `localeToLanguage` function which is called at least **twice** upon opening the administration. Since these entities are associated with one another, this function can be optimised by using a single request with the respective association. This PR achieves this by improving the (single) request.
Before (notice the `language` requests):
After (two requests less):
Open the administration. Look into the browser-dev-tools network tab.
> NEXT-10928 - Optimise requests in `LocaleToLanguageService`

- changelog/_unreleased/2020-09-17-validate-min-max-purchase-quantity.md
- src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js
- src/Administration/Resources/app/administration/src/module/sw-product/snippet/de-DE.json
- src/Administration/Resources/app/administration/src/module/sw-product/snippet/en-GB.json
One currently can save invalid combinations for the min and max purchase values. This PR prevents saving such combinations in the administration.
Implement a validation before saving the product in the administration
Put for example 11 as min order quantity and 10 as max order quantity in a product and save it, it will work but the product in the storefront is kind of broken.
Fixes #22
> NEXT-9322 - check that min purchase does not exceed max purchase

- changelog/_unreleased/2020-09-17-add-missing-order-delivery-state-transitions.md
- src/Core/Migration/Migration1600349343AddDeliveryStateTransitions.php
Add's state transitions from all order delivery states back to open.
> NEXT-9360 - add missing order delivery state transitions

- changelog/_unreleased/2020-09-17-add-keyboard-shortcuts-for-reviews.md
- src/Administration/Resources/app/administration/src/module/sw-review/page/sw-review-detail/index.js
- src/Administration/Resources/app/administration/src/module/sw-review/page/sw-review-detail/sw-review-detail.html.twig
Currently it is not possible to use the keyboard shortcuts for the reviews, to save and cancel the currently selected review.
Add the keyboard shortcuts.
Open a review in the administration and press `ALT + S` (on my machine).
Fixes #32
> NEXT-9202 - Add keyboard shortcuts for reviews

- src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/page/sw-settings-custom-field-set-list/sw-settings-custom-field-set-list.html.twig
Currently, the Custom Fields have no Empty state. This should be added accordingly to the other empty states
Set the `absolute` property on the empty state.
Go to Settings > Custom Fields. Remove all custom fields. You will not see an empty state.
https://github.com/shopwareBoostDay/platform/issues/238
> NEXT-12093 - Fix custom fields empty state

- src/Storefront/Resources/app/storefront/src/scss/component/_filter-panel.scss
- src/Storefront/Resources/views/storefront/component/listing/filter-panel.html.twig
From SEO point of view, h-tags should not be used in the theme. 
Replaced h3 with span tag
https://github.com/shopwareBoostDay/platform/issues/186
> NEXT-12360 - Swap h3 tag in filter panel offcanvas

- changelog/_unreleased/2021-01-14-add-hide-on-product-detail-option-for-properties.md
- src/Administration/Resources/app/administration/src/module/sw-property/component/sw-property-detail-base/sw-property-detail-base.html.twig
- src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-create/index.js
- src/Administration/Resources/app/administration/src/module/sw-property/snippet/de-DE.json
- src/Administration/Resources/app/administration/src/module/sw-property/snippet/en-GB.json
- src/Core/Content/Product/Subscriber/ProductSubscriber.php
- src/Core/Content/Property/PropertyGroupDefinition.php
- src/Core/Content/Property/PropertyGroupEntity.php
- src/Core/Content/Test/Product/Subscriber/ProductLoadedSubscriberTest.php
- src/Core/Migration/Migration1610616655AddVisibleOnDetailToPropertyGroup.php
Allows the admin to hide certain properties from product detail pages.
Adds a checkbox to the Property Group administration view, adds a field to the PropertyGroup entity, filters the 'disabled' property groups out of the sortedProperties in the ProductLoader.
https://user-images.githubusercontent.com/3930922/104585386-358bba00-5664-11eb-9128-131edc9a330e.mov
https://github.com/shopwareBoostDay/platform/issues/251
> NEXT-13262 - Add Hide On Product Detail option for properties

- changelog/_unreleased/2021-01-14-add-data-protection-information-checkbox.md
- src/Core/Checkout/Customer/SalesChannel/RegisterRoute.php
- src/Core/Checkout/Test/Customer/AccountRegistrationServiceTest.php
- src/Core/Migration/Migration1610625925RequireDataProtectionCheckbox.php
- src/Core/System/Resources/config/loginRegistration.xml
- src/Storefront/Resources/app/storefront/src/scss/page/account/_register.scss
- src/Storefront/Resources/views/storefront/component/privacy-notice.html.twig
Allow users to actively accept the privacy policy.
Add a required checkbox (configurable off course) to the registration form/route.
https://youtu.be/q4oBDfqUFbk (file too big for github)
https://github.com/shopwareBoostDay/platform/issues/217
> NEXT-9291 - Add Data Protection Information checkbox

- changelog/_unreleased/2021-01-14-set-total-after-fetching-list-items.md
- src/Administration/Resources/app/administration/src/module/sw-settings/mixin/sw-settings-list.mixin.js
To fix some counter issues in the administration settings pages.
Set the value of total after fetching list items.
Go to settings > documents page for example.
#205
> NEXT-10679 - Set total after fetching list items

- changelog/_unreleased/2021-01-14-add-cancel-button-to-email-template-settings.md
- src/Administration/Resources/app/administration/src/module/sw-mail-template/page/sw-mail-header-footer-detail/index.js
- src/Administration/Resources/app/administration/src/module/sw-mail-template/page/sw-mail-header-footer-detail/sw-mail-header-footer-detail.html.twig
- src/Administration/Resources/app/administration/src/module/sw-mail-template/page/sw-mail-template-detail/index.js
- src/Administration/Resources/app/administration/src/module/sw-mail-template/page/sw-mail-template-detail/sw-mail-template-detail.html.twig
Add cancel buttons to email template settings
Add cancel buttons to email template settings
Go to Settings ->  Email templates, add new or edit a template, Cancel button is missing
> NEXT-11384 - Add cancel button on template settings

- changelog/_unreleased/2021-01-14-use-img-element-for-hero-image-cms-element.md
- src/Storefront/Resources/app/storefront/src/scss/component/_cms-block.scss
- src/Storefront/Resources/views/storefront/section/cms-section-block-container.html.twig
Shopping Experiences:
When choosing a "Hero image" element in a layout, the different generated thumbnail sizes aren't being used, but the original image in its original size. This means that the image is not adjusted, for example in mobile views.
Change the usage of an inline background-image style to the sw_thumbnail twig function.
Due to the way that img's object-fit works, it is not possible to mimic the 'Auto' setting of the block background. This means that elements that currently have 'Auto' set as their background mode will look different.
https://github.com/shopwareBoostDay/platform/issues/230
> NEXT-7986 - Use img element for Hero Image CMS element

- changelog/_unreleased/2021-01-14-add-correct-error-message-on-saving-an-product-with-already-existing-product-no.md
- src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js
- src/Administration/Resources/app/administration/src/module/sw-product/snippet/de-DE.json
- src/Administration/Resources/app/administration/src/module/sw-product/snippet/en-GB.json
When you save/create a product and enter an already existing product no., the error message is not clear.
It shows an error message that the product no. already exists.
-
#241
> NEXT-11401 - Add additional error message on `sw-product` save
